// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BillsColumns holds the columns for the "bills" table.
	BillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "reference_2", Type: field.TypeInt, Nullable: true},
		{Name: "transaction_id", Type: field.TypeString, Default: ""},
		{Name: "tran_amount", Type: field.TypeFloat64, Default: 0},
		{Name: "channel_code", Type: field.TypeString, Default: ""},
		{Name: "sender_bank_code", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "biller_id", Type: field.TypeInt, Nullable: true},
		{Name: "reference_1", Type: field.TypeInt, Nullable: true},
	}
	// BillsTable holds the schema information for the "bills" table.
	BillsTable = &schema.Table{
		Name:       "bills",
		Columns:    BillsColumns,
		PrimaryKey: []*schema.Column{BillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bills_biller_accounts_bills",
				Columns:    []*schema.Column{BillsColumns[9]},
				RefColumns: []*schema.Column{BillerAccountsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "bills_customers_bills",
				Columns:    []*schema.Column{BillsColumns[10]},
				RefColumns: []*schema.Column{CustomersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// BillerAccountsColumns holds the columns for the "biller_accounts" table.
	BillerAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "service_name", Type: field.TypeString, Default: ""},
	}
	// BillerAccountsTable holds the schema information for the "biller_accounts" table.
	BillerAccountsTable = &schema.Table{
		Name:       "biller_accounts",
		Columns:    BillerAccountsColumns,
		PrimaryKey: []*schema.Column{BillerAccountsColumns[0]},
	}
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "first_name", Type: field.TypeString, Default: "Unknown"},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "title_name", Type: field.TypeString, Default: ""},
		{Name: "mobile_number", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BillsTable,
		BillerAccountsTable,
		CustomersTable,
	}
)

func init() {
	BillsTable.ForeignKeys[0].RefTable = BillerAccountsTable
	BillsTable.ForeignKeys[1].RefTable = CustomersTable
}
