// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"kapi/ent/biller_account"
	"kapi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BillerAccountDelete is the builder for deleting a Biller_account entity.
type BillerAccountDelete struct {
	config
	hooks    []Hook
	mutation *BillerAccountMutation
}

// Where appends a list predicates to the BillerAccountDelete builder.
func (bad *BillerAccountDelete) Where(ps ...predicate.Biller_account) *BillerAccountDelete {
	bad.mutation.Where(ps...)
	return bad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bad *BillerAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bad.sqlExec, bad.mutation, bad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bad *BillerAccountDelete) ExecX(ctx context.Context) int {
	n, err := bad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bad *BillerAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(biller_account.Table, sqlgraph.NewFieldSpec(biller_account.FieldID, field.TypeInt))
	if ps := bad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bad.mutation.done = true
	return affected, err
}

// BillerAccountDeleteOne is the builder for deleting a single Biller_account entity.
type BillerAccountDeleteOne struct {
	bad *BillerAccountDelete
}

// Where appends a list predicates to the BillerAccountDelete builder.
func (bado *BillerAccountDeleteOne) Where(ps ...predicate.Biller_account) *BillerAccountDeleteOne {
	bado.bad.mutation.Where(ps...)
	return bado
}

// Exec executes the deletion query.
func (bado *BillerAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := bado.bad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{biller_account.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bado *BillerAccountDeleteOne) ExecX(ctx context.Context) {
	if err := bado.Exec(ctx); err != nil {
		panic(err)
	}
}
