// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kapi/ent/bill"
	"kapi/ent/billdetail"
	"kapi/ent/customer"
	"kapi/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BillDetailQuery is the builder for querying BillDetail entities.
type BillDetailQuery struct {
	config
	ctx          *QueryContext
	order        []billdetail.OrderOption
	inters       []Interceptor
	predicates   []predicate.BillDetail
	withBills    *BillQuery
	withCustomer *CustomerQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BillDetailQuery builder.
func (bdq *BillDetailQuery) Where(ps ...predicate.BillDetail) *BillDetailQuery {
	bdq.predicates = append(bdq.predicates, ps...)
	return bdq
}

// Limit the number of records to be returned by this query.
func (bdq *BillDetailQuery) Limit(limit int) *BillDetailQuery {
	bdq.ctx.Limit = &limit
	return bdq
}

// Offset to start from.
func (bdq *BillDetailQuery) Offset(offset int) *BillDetailQuery {
	bdq.ctx.Offset = &offset
	return bdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bdq *BillDetailQuery) Unique(unique bool) *BillDetailQuery {
	bdq.ctx.Unique = &unique
	return bdq
}

// Order specifies how the records should be ordered.
func (bdq *BillDetailQuery) Order(o ...billdetail.OrderOption) *BillDetailQuery {
	bdq.order = append(bdq.order, o...)
	return bdq
}

// QueryBills chains the current query on the "bills" edge.
func (bdq *BillDetailQuery) QueryBills() *BillQuery {
	query := (&BillClient{config: bdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(billdetail.Table, billdetail.FieldID, selector),
			sqlgraph.To(bill.Table, bill.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, billdetail.BillsTable, billdetail.BillsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCustomer chains the current query on the "customer" edge.
func (bdq *BillDetailQuery) QueryCustomer() *CustomerQuery {
	query := (&CustomerClient{config: bdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(billdetail.Table, billdetail.FieldID, selector),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, billdetail.CustomerTable, billdetail.CustomerColumn),
		)
		fromU = sqlgraph.SetNeighbors(bdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BillDetail entity from the query.
// Returns a *NotFoundError when no BillDetail was found.
func (bdq *BillDetailQuery) First(ctx context.Context) (*BillDetail, error) {
	nodes, err := bdq.Limit(1).All(setContextOp(ctx, bdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{billdetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bdq *BillDetailQuery) FirstX(ctx context.Context) *BillDetail {
	node, err := bdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BillDetail ID from the query.
// Returns a *NotFoundError when no BillDetail ID was found.
func (bdq *BillDetailQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bdq.Limit(1).IDs(setContextOp(ctx, bdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{billdetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bdq *BillDetailQuery) FirstIDX(ctx context.Context) int {
	id, err := bdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BillDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BillDetail entity is found.
// Returns a *NotFoundError when no BillDetail entities are found.
func (bdq *BillDetailQuery) Only(ctx context.Context) (*BillDetail, error) {
	nodes, err := bdq.Limit(2).All(setContextOp(ctx, bdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{billdetail.Label}
	default:
		return nil, &NotSingularError{billdetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bdq *BillDetailQuery) OnlyX(ctx context.Context) *BillDetail {
	node, err := bdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BillDetail ID in the query.
// Returns a *NotSingularError when more than one BillDetail ID is found.
// Returns a *NotFoundError when no entities are found.
func (bdq *BillDetailQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bdq.Limit(2).IDs(setContextOp(ctx, bdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{billdetail.Label}
	default:
		err = &NotSingularError{billdetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bdq *BillDetailQuery) OnlyIDX(ctx context.Context) int {
	id, err := bdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BillDetails.
func (bdq *BillDetailQuery) All(ctx context.Context) ([]*BillDetail, error) {
	ctx = setContextOp(ctx, bdq.ctx, "All")
	if err := bdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BillDetail, *BillDetailQuery]()
	return withInterceptors[[]*BillDetail](ctx, bdq, qr, bdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bdq *BillDetailQuery) AllX(ctx context.Context) []*BillDetail {
	nodes, err := bdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BillDetail IDs.
func (bdq *BillDetailQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bdq.ctx.Unique == nil && bdq.path != nil {
		bdq.Unique(true)
	}
	ctx = setContextOp(ctx, bdq.ctx, "IDs")
	if err = bdq.Select(billdetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bdq *BillDetailQuery) IDsX(ctx context.Context) []int {
	ids, err := bdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bdq *BillDetailQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bdq.ctx, "Count")
	if err := bdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bdq, querierCount[*BillDetailQuery](), bdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bdq *BillDetailQuery) CountX(ctx context.Context) int {
	count, err := bdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bdq *BillDetailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bdq.ctx, "Exist")
	switch _, err := bdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bdq *BillDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := bdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BillDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bdq *BillDetailQuery) Clone() *BillDetailQuery {
	if bdq == nil {
		return nil
	}
	return &BillDetailQuery{
		config:       bdq.config,
		ctx:          bdq.ctx.Clone(),
		order:        append([]billdetail.OrderOption{}, bdq.order...),
		inters:       append([]Interceptor{}, bdq.inters...),
		predicates:   append([]predicate.BillDetail{}, bdq.predicates...),
		withBills:    bdq.withBills.Clone(),
		withCustomer: bdq.withCustomer.Clone(),
		// clone intermediate query.
		sql:  bdq.sql.Clone(),
		path: bdq.path,
	}
}

// WithBills tells the query-builder to eager-load the nodes that are connected to
// the "bills" edge. The optional arguments are used to configure the query builder of the edge.
func (bdq *BillDetailQuery) WithBills(opts ...func(*BillQuery)) *BillDetailQuery {
	query := (&BillClient{config: bdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bdq.withBills = query
	return bdq
}

// WithCustomer tells the query-builder to eager-load the nodes that are connected to
// the "customer" edge. The optional arguments are used to configure the query builder of the edge.
func (bdq *BillDetailQuery) WithCustomer(opts ...func(*CustomerQuery)) *BillDetailQuery {
	query := (&CustomerClient{config: bdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bdq.withCustomer = query
	return bdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChannelCode string `json:"channel_code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BillDetail.Query().
//		GroupBy(billdetail.FieldChannelCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bdq *BillDetailQuery) GroupBy(field string, fields ...string) *BillDetailGroupBy {
	bdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BillDetailGroupBy{build: bdq}
	grbuild.flds = &bdq.ctx.Fields
	grbuild.label = billdetail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChannelCode string `json:"channel_code,omitempty"`
//	}
//
//	client.BillDetail.Query().
//		Select(billdetail.FieldChannelCode).
//		Scan(ctx, &v)
func (bdq *BillDetailQuery) Select(fields ...string) *BillDetailSelect {
	bdq.ctx.Fields = append(bdq.ctx.Fields, fields...)
	sbuild := &BillDetailSelect{BillDetailQuery: bdq}
	sbuild.label = billdetail.Label
	sbuild.flds, sbuild.scan = &bdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BillDetailSelect configured with the given aggregations.
func (bdq *BillDetailQuery) Aggregate(fns ...AggregateFunc) *BillDetailSelect {
	return bdq.Select().Aggregate(fns...)
}

func (bdq *BillDetailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bdq); err != nil {
				return err
			}
		}
	}
	for _, f := range bdq.ctx.Fields {
		if !billdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bdq.path != nil {
		prev, err := bdq.path(ctx)
		if err != nil {
			return err
		}
		bdq.sql = prev
	}
	return nil
}

func (bdq *BillDetailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BillDetail, error) {
	var (
		nodes       = []*BillDetail{}
		withFKs     = bdq.withFKs
		_spec       = bdq.querySpec()
		loadedTypes = [2]bool{
			bdq.withBills != nil,
			bdq.withCustomer != nil,
		}
	)
	if bdq.withBills != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, billdetail.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BillDetail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BillDetail{config: bdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bdq.withBills; query != nil {
		if err := bdq.loadBills(ctx, query, nodes, nil,
			func(n *BillDetail, e *Bill) { n.Edges.Bills = e }); err != nil {
			return nil, err
		}
	}
	if query := bdq.withCustomer; query != nil {
		if err := bdq.loadCustomer(ctx, query, nodes, nil,
			func(n *BillDetail, e *Customer) { n.Edges.Customer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bdq *BillDetailQuery) loadBills(ctx context.Context, query *BillQuery, nodes []*BillDetail, init func(*BillDetail), assign func(*BillDetail, *Bill)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BillDetail)
	for i := range nodes {
		if nodes[i].bill_bill_detail == nil {
			continue
		}
		fk := *nodes[i].bill_bill_detail
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bill.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bill_bill_detail" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bdq *BillDetailQuery) loadCustomer(ctx context.Context, query *CustomerQuery, nodes []*BillDetail, init func(*BillDetail), assign func(*BillDetail, *Customer)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BillDetail)
	for i := range nodes {
		fk := nodes[i].CustomerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(customer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "customer_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bdq *BillDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bdq.querySpec()
	_spec.Node.Columns = bdq.ctx.Fields
	if len(bdq.ctx.Fields) > 0 {
		_spec.Unique = bdq.ctx.Unique != nil && *bdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bdq.driver, _spec)
}

func (bdq *BillDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(billdetail.Table, billdetail.Columns, sqlgraph.NewFieldSpec(billdetail.FieldID, field.TypeInt))
	_spec.From = bdq.sql
	if unique := bdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bdq.path != nil {
		_spec.Unique = true
	}
	if fields := bdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billdetail.FieldID)
		for i := range fields {
			if fields[i] != billdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if bdq.withCustomer != nil {
			_spec.Node.AddColumnOnce(billdetail.FieldCustomerID)
		}
	}
	if ps := bdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bdq *BillDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bdq.driver.Dialect())
	t1 := builder.Table(billdetail.Table)
	columns := bdq.ctx.Fields
	if len(columns) == 0 {
		columns = billdetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bdq.sql != nil {
		selector = bdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bdq.ctx.Unique != nil && *bdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bdq.predicates {
		p(selector)
	}
	for _, p := range bdq.order {
		p(selector)
	}
	if offset := bdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BillDetailGroupBy is the group-by builder for BillDetail entities.
type BillDetailGroupBy struct {
	selector
	build *BillDetailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bdgb *BillDetailGroupBy) Aggregate(fns ...AggregateFunc) *BillDetailGroupBy {
	bdgb.fns = append(bdgb.fns, fns...)
	return bdgb
}

// Scan applies the selector query and scans the result into the given value.
func (bdgb *BillDetailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bdgb.build.ctx, "GroupBy")
	if err := bdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BillDetailQuery, *BillDetailGroupBy](ctx, bdgb.build, bdgb, bdgb.build.inters, v)
}

func (bdgb *BillDetailGroupBy) sqlScan(ctx context.Context, root *BillDetailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bdgb.fns))
	for _, fn := range bdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bdgb.flds)+len(bdgb.fns))
		for _, f := range *bdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BillDetailSelect is the builder for selecting fields of BillDetail entities.
type BillDetailSelect struct {
	*BillDetailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bds *BillDetailSelect) Aggregate(fns ...AggregateFunc) *BillDetailSelect {
	bds.fns = append(bds.fns, fns...)
	return bds
}

// Scan applies the selector query and scans the result into the given value.
func (bds *BillDetailSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bds.ctx, "Select")
	if err := bds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BillDetailQuery, *BillDetailSelect](ctx, bds.BillDetailQuery, bds, bds.inters, v)
}

func (bds *BillDetailSelect) sqlScan(ctx context.Context, root *BillDetailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bds.fns))
	for _, fn := range bds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
