// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kapi/ent/bill"
	"kapi/ent/billdetail"
	"kapi/ent/customer"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomerCreate is the builder for creating a Customer entity.
type CustomerCreate struct {
	config
	mutation *CustomerMutation
	hooks    []Hook
}

// SetFirstName sets the "first_name" field.
func (cc *CustomerCreate) SetFirstName(s string) *CustomerCreate {
	cc.mutation.SetFirstName(s)
	return cc
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableFirstName(s *string) *CustomerCreate {
	if s != nil {
		cc.SetFirstName(*s)
	}
	return cc
}

// SetLastName sets the "last_name" field.
func (cc *CustomerCreate) SetLastName(s string) *CustomerCreate {
	cc.mutation.SetLastName(s)
	return cc
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableLastName(s *string) *CustomerCreate {
	if s != nil {
		cc.SetLastName(*s)
	}
	return cc
}

// SetTitleName sets the "title_name" field.
func (cc *CustomerCreate) SetTitleName(s string) *CustomerCreate {
	cc.mutation.SetTitleName(s)
	return cc
}

// SetNillableTitleName sets the "title_name" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableTitleName(s *string) *CustomerCreate {
	if s != nil {
		cc.SetTitleName(*s)
	}
	return cc
}

// SetMobileNumber sets the "mobile_number" field.
func (cc *CustomerCreate) SetMobileNumber(s string) *CustomerCreate {
	cc.mutation.SetMobileNumber(s)
	return cc
}

// SetNillableMobileNumber sets the "mobile_number" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableMobileNumber(s *string) *CustomerCreate {
	if s != nil {
		cc.SetMobileNumber(*s)
	}
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *CustomerCreate) SetCreatedAt(t time.Time) *CustomerCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableCreatedAt(t *time.Time) *CustomerCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CustomerCreate) SetID(i int) *CustomerCreate {
	cc.mutation.SetID(i)
	return cc
}

// AddBillDetailIDs adds the "bill_details" edge to the BillDetail entity by IDs.
func (cc *CustomerCreate) AddBillDetailIDs(ids ...int) *CustomerCreate {
	cc.mutation.AddBillDetailIDs(ids...)
	return cc
}

// AddBillDetails adds the "bill_details" edges to the BillDetail entity.
func (cc *CustomerCreate) AddBillDetails(b ...*BillDetail) *CustomerCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return cc.AddBillDetailIDs(ids...)
}

// AddBillIDs adds the "bills" edge to the Bill entity by IDs.
func (cc *CustomerCreate) AddBillIDs(ids ...int) *CustomerCreate {
	cc.mutation.AddBillIDs(ids...)
	return cc
}

// AddBills adds the "bills" edges to the Bill entity.
func (cc *CustomerCreate) AddBills(b ...*Bill) *CustomerCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return cc.AddBillIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (cc *CustomerCreate) Mutation() *CustomerMutation {
	return cc.mutation
}

// Save creates the Customer in the database.
func (cc *CustomerCreate) Save(ctx context.Context) (*Customer, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CustomerCreate) SaveX(ctx context.Context) *Customer {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CustomerCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CustomerCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CustomerCreate) defaults() {
	if _, ok := cc.mutation.FirstName(); !ok {
		v := customer.DefaultFirstName
		cc.mutation.SetFirstName(v)
	}
	if _, ok := cc.mutation.LastName(); !ok {
		v := customer.DefaultLastName
		cc.mutation.SetLastName(v)
	}
	if _, ok := cc.mutation.TitleName(); !ok {
		v := customer.DefaultTitleName
		cc.mutation.SetTitleName(v)
	}
	if _, ok := cc.mutation.MobileNumber(); !ok {
		v := customer.DefaultMobileNumber
		cc.mutation.SetMobileNumber(v)
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := customer.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CustomerCreate) check() error {
	if _, ok := cc.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Customer.first_name"`)}
	}
	if _, ok := cc.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`ent: missing required field "Customer.last_name"`)}
	}
	if _, ok := cc.mutation.TitleName(); !ok {
		return &ValidationError{Name: "title_name", err: errors.New(`ent: missing required field "Customer.title_name"`)}
	}
	if _, ok := cc.mutation.MobileNumber(); !ok {
		return &ValidationError{Name: "mobile_number", err: errors.New(`ent: missing required field "Customer.mobile_number"`)}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Customer.created_at"`)}
	}
	return nil
}

func (cc *CustomerCreate) sqlSave(ctx context.Context) (*Customer, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CustomerCreate) createSpec() (*Customer, *sqlgraph.CreateSpec) {
	var (
		_node = &Customer{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(customer.Table, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.FirstName(); ok {
		_spec.SetField(customer.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := cc.mutation.LastName(); ok {
		_spec.SetField(customer.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := cc.mutation.TitleName(); ok {
		_spec.SetField(customer.FieldTitleName, field.TypeString, value)
		_node.TitleName = value
	}
	if value, ok := cc.mutation.MobileNumber(); ok {
		_spec.SetField(customer.FieldMobileNumber, field.TypeString, value)
		_node.MobileNumber = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(customer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := cc.mutation.BillDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.BillDetailsTable,
			Columns: []string{customer.BillDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billdetail.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.BillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.BillsTable,
			Columns: []string{customer.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CustomerCreateBulk is the builder for creating many Customer entities in bulk.
type CustomerCreateBulk struct {
	config
	builders []*CustomerCreate
}

// Save creates the Customer entities in the database.
func (ccb *CustomerCreateBulk) Save(ctx context.Context) ([]*Customer, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Customer, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CustomerCreateBulk) SaveX(ctx context.Context) []*Customer {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CustomerCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CustomerCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
