// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kapi/ent/bill"
	"kapi/ent/biller_account"
	"kapi/ent/customer"
	"kapi/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	billFields := schema.Bill{}.Fields()
	_ = billFields
	// billDescTransactionID is the schema descriptor for transaction_id field.
	billDescTransactionID := billFields[4].Descriptor()
	// bill.DefaultTransactionID holds the default value on creation for the transaction_id field.
	bill.DefaultTransactionID = billDescTransactionID.Default.(string)
	// billDescTranAmount is the schema descriptor for tran_amount field.
	billDescTranAmount := billFields[5].Descriptor()
	// bill.DefaultTranAmount holds the default value on creation for the tran_amount field.
	bill.DefaultTranAmount = billDescTranAmount.Default.(float64)
	// billDescChannelCode is the schema descriptor for channel_code field.
	billDescChannelCode := billFields[6].Descriptor()
	// bill.DefaultChannelCode holds the default value on creation for the channel_code field.
	bill.DefaultChannelCode = billDescChannelCode.Default.(string)
	// billDescSenderBankCode is the schema descriptor for sender_bank_code field.
	billDescSenderBankCode := billFields[7].Descriptor()
	// bill.DefaultSenderBankCode holds the default value on creation for the sender_bank_code field.
	bill.DefaultSenderBankCode = billDescSenderBankCode.Default.(string)
	// billDescStatus is the schema descriptor for status field.
	billDescStatus := billFields[8].Descriptor()
	// bill.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	bill.StatusValidator = billDescStatus.Validators[0].(func(string) error)
	// billDescCreatedAt is the schema descriptor for created_at field.
	billDescCreatedAt := billFields[9].Descriptor()
	// bill.DefaultCreatedAt holds the default value on creation for the created_at field.
	bill.DefaultCreatedAt = billDescCreatedAt.Default.(func() time.Time)
	// billDescUpdatedAt is the schema descriptor for updated_at field.
	billDescUpdatedAt := billFields[10].Descriptor()
	// bill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bill.DefaultUpdatedAt = billDescUpdatedAt.Default.(func() time.Time)
	// bill.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bill.UpdateDefaultUpdatedAt = billDescUpdatedAt.UpdateDefault.(func() time.Time)
	biller_accountFields := schema.Biller_account{}.Fields()
	_ = biller_accountFields
	// biller_accountDescName is the schema descriptor for name field.
	biller_accountDescName := biller_accountFields[1].Descriptor()
	// biller_account.DefaultName holds the default value on creation for the name field.
	biller_account.DefaultName = biller_accountDescName.Default.(string)
	// biller_accountDescServiceName is the schema descriptor for service_name field.
	biller_accountDescServiceName := biller_accountFields[2].Descriptor()
	// biller_account.DefaultServiceName holds the default value on creation for the service_name field.
	biller_account.DefaultServiceName = biller_accountDescServiceName.Default.(string)
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescFirstName is the schema descriptor for first_name field.
	customerDescFirstName := customerFields[1].Descriptor()
	// customer.DefaultFirstName holds the default value on creation for the first_name field.
	customer.DefaultFirstName = customerDescFirstName.Default.(string)
	// customerDescLastName is the schema descriptor for last_name field.
	customerDescLastName := customerFields[2].Descriptor()
	// customer.DefaultLastName holds the default value on creation for the last_name field.
	customer.DefaultLastName = customerDescLastName.Default.(string)
	// customerDescTitleName is the schema descriptor for title_name field.
	customerDescTitleName := customerFields[3].Descriptor()
	// customer.DefaultTitleName holds the default value on creation for the title_name field.
	customer.DefaultTitleName = customerDescTitleName.Default.(string)
	// customerDescMobileNumber is the schema descriptor for mobile_number field.
	customerDescMobileNumber := customerFields[4].Descriptor()
	// customer.DefaultMobileNumber holds the default value on creation for the mobile_number field.
	customer.DefaultMobileNumber = customerDescMobileNumber.Default.(string)
	// customerDescCreatedAt is the schema descriptor for created_at field.
	customerDescCreatedAt := customerFields[5].Descriptor()
	// customer.DefaultCreatedAt holds the default value on creation for the created_at field.
	customer.DefaultCreatedAt = customerDescCreatedAt.Default.(func() time.Time)
}
