// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kapi/ent/bill"
	"kapi/ent/predicate"
	"kapi/ent/store"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreUpdate is the builder for updating Store entities.
type StoreUpdate struct {
	config
	hooks    []Hook
	mutation *StoreMutation
}

// Where appends a list predicates to the StoreUpdate builder.
func (su *StoreUpdate) Where(ps ...predicate.Store) *StoreUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetAccountName sets the "account_name" field.
func (su *StoreUpdate) SetAccountName(s string) *StoreUpdate {
	su.mutation.SetAccountName(s)
	return su
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (su *StoreUpdate) SetNillableAccountName(s *string) *StoreUpdate {
	if s != nil {
		su.SetAccountName(*s)
	}
	return su
}

// SetServiceName sets the "service_name" field.
func (su *StoreUpdate) SetServiceName(s string) *StoreUpdate {
	su.mutation.SetServiceName(s)
	return su
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (su *StoreUpdate) SetNillableServiceName(s *string) *StoreUpdate {
	if s != nil {
		su.SetServiceName(*s)
	}
	return su
}

// AddBillIDs adds the "bills" edge to the Bill entity by IDs.
func (su *StoreUpdate) AddBillIDs(ids ...int) *StoreUpdate {
	su.mutation.AddBillIDs(ids...)
	return su
}

// AddBills adds the "bills" edges to the Bill entity.
func (su *StoreUpdate) AddBills(b ...*Bill) *StoreUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return su.AddBillIDs(ids...)
}

// Mutation returns the StoreMutation object of the builder.
func (su *StoreUpdate) Mutation() *StoreMutation {
	return su.mutation
}

// ClearBills clears all "bills" edges to the Bill entity.
func (su *StoreUpdate) ClearBills() *StoreUpdate {
	su.mutation.ClearBills()
	return su
}

// RemoveBillIDs removes the "bills" edge to Bill entities by IDs.
func (su *StoreUpdate) RemoveBillIDs(ids ...int) *StoreUpdate {
	su.mutation.RemoveBillIDs(ids...)
	return su
}

// RemoveBills removes "bills" edges to Bill entities.
func (su *StoreUpdate) RemoveBills(b ...*Bill) *StoreUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return su.RemoveBillIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StoreUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StoreUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StoreUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StoreUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(store.Table, store.Columns, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.AccountName(); ok {
		_spec.SetField(store.FieldAccountName, field.TypeString, value)
	}
	if value, ok := su.mutation.ServiceName(); ok {
		_spec.SetField(store.FieldServiceName, field.TypeString, value)
	}
	if su.mutation.BillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.BillsTable,
			Columns: []string{store.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedBillsIDs(); len(nodes) > 0 && !su.mutation.BillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.BillsTable,
			Columns: []string{store.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.BillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.BillsTable,
			Columns: []string{store.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{store.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StoreUpdateOne is the builder for updating a single Store entity.
type StoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StoreMutation
}

// SetAccountName sets the "account_name" field.
func (suo *StoreUpdateOne) SetAccountName(s string) *StoreUpdateOne {
	suo.mutation.SetAccountName(s)
	return suo
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableAccountName(s *string) *StoreUpdateOne {
	if s != nil {
		suo.SetAccountName(*s)
	}
	return suo
}

// SetServiceName sets the "service_name" field.
func (suo *StoreUpdateOne) SetServiceName(s string) *StoreUpdateOne {
	suo.mutation.SetServiceName(s)
	return suo
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableServiceName(s *string) *StoreUpdateOne {
	if s != nil {
		suo.SetServiceName(*s)
	}
	return suo
}

// AddBillIDs adds the "bills" edge to the Bill entity by IDs.
func (suo *StoreUpdateOne) AddBillIDs(ids ...int) *StoreUpdateOne {
	suo.mutation.AddBillIDs(ids...)
	return suo
}

// AddBills adds the "bills" edges to the Bill entity.
func (suo *StoreUpdateOne) AddBills(b ...*Bill) *StoreUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return suo.AddBillIDs(ids...)
}

// Mutation returns the StoreMutation object of the builder.
func (suo *StoreUpdateOne) Mutation() *StoreMutation {
	return suo.mutation
}

// ClearBills clears all "bills" edges to the Bill entity.
func (suo *StoreUpdateOne) ClearBills() *StoreUpdateOne {
	suo.mutation.ClearBills()
	return suo
}

// RemoveBillIDs removes the "bills" edge to Bill entities by IDs.
func (suo *StoreUpdateOne) RemoveBillIDs(ids ...int) *StoreUpdateOne {
	suo.mutation.RemoveBillIDs(ids...)
	return suo
}

// RemoveBills removes "bills" edges to Bill entities.
func (suo *StoreUpdateOne) RemoveBills(b ...*Bill) *StoreUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return suo.RemoveBillIDs(ids...)
}

// Where appends a list predicates to the StoreUpdate builder.
func (suo *StoreUpdateOne) Where(ps ...predicate.Store) *StoreUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StoreUpdateOne) Select(field string, fields ...string) *StoreUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Store entity.
func (suo *StoreUpdateOne) Save(ctx context.Context) (*Store, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StoreUpdateOne) SaveX(ctx context.Context) *Store {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StoreUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StoreUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StoreUpdateOne) sqlSave(ctx context.Context) (_node *Store, err error) {
	_spec := sqlgraph.NewUpdateSpec(store.Table, store.Columns, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Store.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, store.FieldID)
		for _, f := range fields {
			if !store.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != store.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.AccountName(); ok {
		_spec.SetField(store.FieldAccountName, field.TypeString, value)
	}
	if value, ok := suo.mutation.ServiceName(); ok {
		_spec.SetField(store.FieldServiceName, field.TypeString, value)
	}
	if suo.mutation.BillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.BillsTable,
			Columns: []string{store.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedBillsIDs(); len(nodes) > 0 && !suo.mutation.BillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.BillsTable,
			Columns: []string{store.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.BillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.BillsTable,
			Columns: []string{store.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Store{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{store.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
