// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bill is the predicate function for bill builders.
type Bill func(*sql.Selector)

// Biller_account is the predicate function for biller_account builders.
type Biller_account func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)
