// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bill is the predicate function for bill builders.
type Bill func(*sql.Selector)

// BillDetail is the predicate function for billdetail builders.
type BillDetail func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Store is the predicate function for store builders.
type Store func(*sql.Selector)
